name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install -g pnpm
    - name: Run pnpm install.
      run: pnpm install
    - name: Run npm run build
      run: pnpm run build --if-present
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag next-web-app:$(date +%s)
